language: node_js

sudo: required
services:
  - docker

before_install:
  - docker build -t azeemz/docker-react -f Dockerfile.dev .

script:
  - docker run azeemz/docker-react "CI=true npm test"
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "..."
#   bucket_path: "docker-react"
#   on:
#     branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#       secure: "$AWS_SECRET_KEY"
