language: node_js
node_js:
  - 15.3.0

sudo: required
services:
  - docker

before_install:
  - docker build -t azeemz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true azeemz/docker-react npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "..."
#   bucket_path: "docker-react"
#   on:
#     branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#       secure: "$AWS_SECRET_KEY"
